[package]
name = "bloopy"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
ratatui = "0.23"
rasteroid = "0.1.1"
image = "0.25.6"
viuer = { version = "0.9.2", features = ["print-file"] }
